### ISSUE TITLE
Fix highlighting for direct assignation of sets and parameters

### ISSUE THREAD

**Issue by lolow** [lolow/gams#1]
when sets and parameters are assigned values with the following syntax / value / they highlighting does not work properly

**Comment by xhokir** [comment]
I had a similar issue with scalars. I think this is also fixed with my latest pull request in commit [7c71016](https://github.com/lolow/gams/pull/3/commits/7c71016719ee82eaa440245a656ae72a7166594a) Can you check this also works for you ?

**Comment by lolow** [comment]
Hi, yes it is working. thanks!
