### ISSUE TITLE
Custom comment characters

### ISSUE THREAD

**Issue by lolow** [lolow/gams#2]
Is there a way to turn off the highlighting of {curly brackets} as comments and keep them as normal code? My code uses them in sum{} and other equations, not as comments.

**Comment by xhokir** [comment]
This has been fixed in my latest pull request [29f5a44](https://github.com/lolow/gams/pull/3/commits/29f5a44e571896ab22e139923d71e0af3dbf14d0) Could you check this also works for you?

**Comment by lolow** [comment]
working, thanks!
