### ISSUE TITLE
Publish the extension on https://open-vsx.org/

### ISSUE THREAD

**Issue by christophe-gouel** [lolow/gams#4]
Hi,

Thanks a lot for your extension.

Could you consider publishing it on <https://open-vsx.org/>? 

It would help with GAMS on VS Code on the cloud. I am setting up GAMS on <https://www.gitpod.io>, but since the extension is not on open vsx I cannot have the support for gms files in vs code in gitpod (see <https://www.gitpod.io/docs/ides-and-editors/vscode-extensions#where-do-i-find-extensions>).

Best,
Christophe

**Comment by lolow** [comment]
Hi,
I see. I did not know about this repository and I think it would be good to publish it there. I let you know when it is done.
Best,
Laurent

**Comment by lolow** [comment]
the extension is now available at https://open-vsx.org/extension/lolow/gams

**Comment by christophe-gouel** [comment]
Great! 

Thanks for your reactivity. It works perfectly now.
